### ISSUE TITLE
Some non-builder droids have Constructing and Repairing roles

### ISSUE THREAD

**Issue by Moumix3** [mipen/Mechanical-Defence-2#14]
See attached image

This affects Mining Droid, Grower Droid, Crafting Droid and Cooking Droid.

With those roles enabled, they won't automatically build or repair anything, but they can be manually ordered to do so.

![ss 2015-03-09 at 09 48 03](https://cloud.githubusercontent.com/assets/11393498/6565201/52660922-c6a6-11e4-8b58-aa070ed2aa73.jpg)

**Comment by Moumix3** [comment]
Tested on vanilla game with only Mechanical Defense 2 - Version 5 installed.

**Comment by mipen** [comment]
As far as I'm aware, there is no way to stop this from happening. It is related to how to game determines what a colonist can and cannot do. Basically, every work type has some work tags attached to it, and if the colonist doesn't have all of those worktags, then they cannot do the work. Building and repairing both only require the ManualSkilled tag, whereas something like crafting requires both ManualSkilled and Crafting, which means that building and repairing will be displayed in its overview. I have written a custom work finder for droids so that they only automatically do the jobs they are supposed to do, but there is unfortunately no way for me to disable the player from forcing them to do things they aren't supposed to do
